name: GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ROOT: tools

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install and build
        run: |
          npm install wasm-pack
          ./node_modules/.bin/wasm-pack build --target=web --out-name wasm --out-dir ./static

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: static
